name: Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build, tag and push docker image
        run: |
          docker build -t ubuntu-opencv .
          docker tag ubuntu-opencv ghcr.io/crowdstress/ubuntu-opencv:latest
          docker push ghcr.io/crowdstress/ubuntu-opencv:latest

  rust:
    needs: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build, tag and push docker image
        run: |
          docker build -t rust-opencv .
          docker tag rust-opencv ghcr.io/crowdstress/rust-opencv:latest
          docker push ghcr.io/crowdstress/rust-opencv:latest
